from flask import Flask, request, jsonify, render_template  # ADDED render_template
import re

app = Flask(__name__)


# VERY SMALL dictionary - only what we need
WORDS = {
    "hello", "world", "i", "a", "in", "this", 
    "the", "be", "to", "of", "and", "hello", "world", "test", "spell", "check", "the", "be", "to", "of", "and", "a",
    
    # 1000+ Common English words
    "about", "above", "across", "act", "active", "activity", "add", "afraid", "after", "again",
    "age", "ago", "agree", "air", "all", "alone", "along", "already", "also", "always",
    "am", "amount", "an", "angry", "animal", "another", "answer", "any", "anyone", "anything",
    "appear", "apple", "are", "area", "arm", "army", "around", "arrive", "art", "as",
    "ask", "at", "attack", "attention", "aunt", "autumn", "away", "baby", "back", "bad",
    "bag", "ball", "bank", "base", "basket", "bath", "bean", "bear", "beautiful", "bed",
    "bedroom", "bee", "beef", "beer", "before", "begin", "behind", "bell", "below", "best",
    "better", "between", "big", "bird", "birth", "birthday", "bit", "bite", "black", "bleed",
    "block", "blood", "blow", "blue", "board", "boat", "body", "bone", "book", "border",
    "born", "borrow", "both", "bottle", "bottom", "bowl", "box", "boy", "branch", "brave",
    "bread", "break", "breakfast", "breathe", "bridge", "bright", "bring", "brother", "brown", "brush",
    "build", "burn", "business", "busy", "but", "butter", "buy", "by", "cake", "call",
    "can", "candle", "cap", "car", "card", "care", "carry", "case", "cat", "catch",
    "cause", "cell", "cent", "center", "century", "certain", "chair", "chance", "change", "character",
    "charge", "cheap", "cheese", "chest", "chicken", "child", "children", "chocolate", "choice", "choose",
    "church", "circle", "city", "claim", "class", "clean", "clear", "climb", "clock", "close",
    "cloth", "clothes", "cloud", "club", "coach", "coast", "coat", "coffee", "cold", "collect",
    "college", "color", "combine", "come", "comfort", "committee", "common", "company", "compare", "competition",
    "complete", "computer", "condition", "consider", "contain", "continue", "control", "cook", "cool", "copy",
    "corner", "correct", "cost", "could", "count", "country", "couple", "course", "court", "cover",
    "crash", "crazy", "cream", "create", "cross", "crowd", "cry", "cup", "current", "cut",
    "dad", "dance", "danger", "dark", "daughter", "day", "dead", "deal", "dear", "death",
    "decide", "decision", "deep", "degree", "depend", "describe", "design", "detail", "develop", "die",
    "difference", "different", "difficult", "dinner", "direct", "direction", "dirty", "discover", "discuss", "disease",
    "dish", "doctor", "dog", "door", "double", "doubt", "down", "draw", "dream", "dress",
    "drink", "drive", "drop", "drug", "dry", "during", "each", "ear", "early", "earn",
    "earth", "east", "easy", "eat", "education", "effect", "egg", "eight", "either", "electric",
    "element", "else", "employ", "empty", "end", "enemy", "energy", "engine", "english", "enjoy",
    "enough", "enter", "environment", "equal", "especially", "even", "evening", "event", "ever", "every",
    "everyone", "everything", "exact", "example", "except", "excite", "excuse", "exercise", "exist", "expect",
    "experience", "explain", "express", "eye", "face", "fact", "fail", "fall", "family", "famous",
    "far", "farm", "fast", "father", "fear", "feed", "feel", "female", "few", "field",
    "fight", "figure", "fill", "film", "final", "find", "fine", "finger", "finish", "fire",
    "first", "fish", "fit", "five", "fix", "flat", "floor", "fly", "follow", "food",
    "foot", "force", "foreign", "forget", "form", "former", "forward", "four", "free", "fresh",
    "friend", "from", "front", "fruit", "full", "fun", "function", "funny", "future", "game",
    "garden", "gas", "general", "gentleman", "get", "girl", "give", "glad", "glass", "god",
    "gold", "good", "government", "grand", "grass", "great", "green", "ground", "group", "grow",
    "guess", "gun", "guy", "hair", "half", "hall", "hand", "happen", "happy", "hard",
    "hat", "hate", "have", "he", "head", "health", "hear", "heart", "heat", "heavy",
    "hell", "help", "her", "here", "herself", "high", "him", "himself", "his", "history",
    "hit", "hold", "hole", "holiday", "home", "hope", "horse", "hospital", "hot", "hotel",
    "hour", "house", "how", "however", "huge", "human", "hundred", "husband", "i", "ice",
    "idea", "if", "ignore", "ill", "image", "imagine", "importance", "important", "improve", "in",
    "include", "income", "increase", "indeed", "individual", "industry", "inform", "inside", "instead", "interest",
    "into", "introduce", "invest", "invite", "involve", "iron", "island", "issue", "it", "item",
    "its", "itself", "job", "join", "journey", "judge", "jump", "just", "keep", "key",
    "kid", "kill", "kind", "king", "kitchen", "knee", "knife", "know", "knowledge", "labor",
    "lack", "lady", "lake", "land", "language", "large", "last", "late", "laugh", "law",
    "lay", "lead", "leader", "learn", "least", "leave", "left", "leg", "legal", "less",
    "let", "letter", "level", "library", "lie", "life", "light", "like", "likely", "limit",
    "line", "link", "lip", "list", "listen", "little", "live", "local", "long", "look",
    "lord", "lose", "loss", "lot", "love", "low", "luck", "lunch", "machine", "main",
    "major", "make", "man", "manage", "many", "map", "mark", "market", "marry", "match",
    "material", "matter", "may", "maybe", "me", "meal", "mean", "measure", "meat", "media",
    "medical", "meet", "member", "memory", "mention", "message", "method", "middle", "might", "mile",
    "military", "milk", "million", "mind", "minute", "miss", "mistake", "mix", "model", "modern",
    "moment", "money", "month", "more", "morning", "most", "mother", "mountain", "mouth", "move",
    "much", "music", "must", "my", "myself", "name", "nation", "national", "natural", "nature",
    "near", "nearly", "necessary", "need", "neighbor", "neither", "network", "never", "new", "news",
    "newspaper", "next", "nice", "night", "no", "nobody", "noise", "none", "nor", "north",
    "nose", "not", "note", "nothing", "notice", "now", "number", "obvious", "off", "offer",
    "office", "officer", "often", "oil", "ok", "old", "on", "once", "one", "only",
    "onto", "open", "operate", "opinion", "opportunity", "or", "order", "organization", "original", "other",
    "otherwise", "our", "out", "outside", "over", "own", "owner", "page", "pain", "paint",
    "pair", "paper", "parent", "park", "part", "particular", "party", "pass", "past", "path",
    "patient", "pattern", "pay", "peace", "people", "per", "percent", "perfect", "perform", "perhaps",
    "period", "person", "personal", "phone", "photo", "physical", "pick", "picture", "piece", "place",
    "plan", "plant", "play", "player", "please", "pleasure", "plenty", "point", "police", "policy",
    "political", "pool", "poor", "popular", "population", "position", "positive", "possible", "post", "potato",
    "pound", "power", "practice", "prepare", "present", "president", "pressure", "pretty", "prevent", "price",
    "prince", "principle", "private", "probably", "problem", "process", "produce", "product", "production", "professional",
    "professor", "program", "project", "property", "protect", "prove", "provide", "public", "pull", "purpose",
    "push", "put", "quality", "question", "quick", "quickly", "quiet", "quite", "race", "radio",
    "rain", "raise", "range", "rate", "rather", "reach", "read", "ready", "real", "reality",
    "realize", "really", "reason", "receive", "recent", "recently", "recognize", "record", "red", "reduce",
    "reflect", "region", "relate", "relationship", "relative", "religious", "remain", "remember", "remove", "report",
    "represent", "republican", "require", "research", "resource", "respond", "response", "responsibility", "rest", "result",
    "return", "reveal", "rich", "right", "ring", "rise", "risk", "road", "rock", "role",
    "room", "rule", "run", "safe", "sale", "same", "sample", "save", "say", "scene",
    "school", "science", "scientist", "score", "sea", "season", "seat", "second", "section", "security",
    "see", "seek", "seem", "sell", "send", "senior", "sense", "series", "serious", "serve",
    "service", "set", "seven", "several", "sex", "sexual", "shake", "shall", "shape", "share",
    "she", "sheet", "ship", "shoot", "shop", "short", "shot", "should", "shoulder", "show",
    "side", "sign", "significant", "similar", "simple", "simply", "since", "sing", "single", "sister",
    "sit", "site", "situation", "six", "size", "skill", "skin", "small", "smile", "so",
    "social", "society", "soldier", "some", "somebody", "someone", "something", "sometimes", "son", "song",
    "soon", "sort", "sound", "source", "south", "southern", "space", "speak", "special", "specific",
    "speech", "spend", "sport", "spring", "staff", "stage", "stand", "standard", "star", "start",
    "state", "statement", "station", "stay", "step", "still", "stock", "stop", "store", "story",
    "strategy", "street", "strong", "structure", "student", "study", "stuff", "style", "subject", "success",
    "successful", "such", "suddenly", "suffer", "suggest", "summer", "support", "sure", "surface", "system",
    "table", "take", "talk", "task", "tax", "teach", "teacher", "team", "technology", "television",
    "tell", "ten", "tend", "term", "test", "than", "thank", "that", "their", "them",
    "themselves", "then", "theory", "there", "these", "they", "thing", "think", "third", "this",
    "those", "though", "thought", "thousand", "threat", "three", "through", "throughout", "throw", "thus",
    "time", "today", "together", "tonight", "too", "top", "total", "touch", "tough", "toward",
    "town", "trade", "traditional", "training", "travel", "treat", "treatment", "tree", "trial", "trip",
    "trouble", "true", "truth", "try", "turn", "tv", "two", "type", "under", "understand",
    "unit", "until", "up", "upon", "us", "use", "usually", "value", "various", "very",
    "victim", "view", "village", "violence", "visit", "voice", "vote", "wait", "walk", "wall",
    "want", "war", "watch", "water", "way", "we", "weapon", "wear", "week", "weight",
    "well", "west", "western", "what", "whatever", "when", "where", "whether", "which", "while",
    "white", "who", "whole", "whom", "whose", "why", "wide", "wife", "will", "win",
    "wind", "window", "wish", "with", "within", "without", "woman", "wonder", "word", "work",
    "worker", "world", "worry", "would", "write", "writer", "wrong", "yard", "yeah", "year",
    "yes", "yet", "you", "young", "your", "yourself", "zero", "zoo", "ability", "able",
    "abroad", "absolute", "academic", "accept", "access", "accident", "account", "accurate", "achieve", "acknowledge",
    "acquire", "action", "active", "actor", "actress", "actual", "addition", "address", "adjust", "administration",
    "admit", "adult", "advance", "advantage", "advertise", "advice", "advise", "affair", "affect", "afford",
    "afternoon", "again", "against", "agency", "agenda", "agent", "agree", "ahead", "aid", "aim",
    "aircraft", "airline", "airport", "alarm", "album", "alcohol", "alive", "allow", "almost", "alone",
    "along", "already", "alright", "although", "always", "amazing", "among", "amount", "analysis", "analyze",
    "ancient", "anger", "angle", "angry", "animal", "announce", "annual", "another", "answer", "anticipate",
    "anxiety", "any", "anybody", "anyone", "anything", "anyway", "anywhere", "apart", "apartment", "apparent",
    "appear", "appearance", "apple", "application", "apply", "appoint", "appointment", "appreciate", "approach", "appropriate",
    "approval", "approve", "approximately", "architect", "area", "argue", "argument", "arise", "arm", "armed",
    "army", "around", "arrange", "arrangement", "arrest", "arrival", "arrive", "art", "article", "artist",
    "artistic", "as", "ashamed", "aside", "ask", "asleep", "aspect", "assess", "assessment", "asset",
    "assign", "assignment", "assist", "assistance", "assistant", "associate", "association", "assume", "assumption", "assure",
    "at", "atmosphere", "attach", "attack", "attempt", "attend", "attention", "attitude", "attorney", "attract",
    "attractive", "audience", "author", "authority", "auto", "available", "average", "avoid", "award", "aware",
    "awareness", "away", "awful", "baby", "back", "background", "bad", "badly", "bag", "bake",
    "balance", "ball", "ban", "band", "bank", "bar", "barely", "barrier", "base", "basic",
    "basically", "basis", "basket", "bath", "bathroom", "battle", "be", "beach", "bean", "bear",
    "beat", "beautiful", "beauty", "because", "become", "bed", "bedroom", "beer", "before", "begin",
    "beginning", "behavior", "behind", "being", "belief", "believe", "bell", "belong", "below", "belt",
    "bench", "bend", "beneath", "benefit", "beside", "besides", "best", "bet", "better", "between",
    "beyond", "bias", "bicycle", "bid", "big", "bike", "bill", "billion", "bind", "biological",
    "bird", "birth", "birthday", "bit", "bite", "bitter", "black", "blade", "blame", "blank",
    "blanket", "blast", "bleed", "blind", "block", "blood", "blow", "blue", "board", "boat",
    "body", "bomb", "bond", "bone", "book", "boom", "boot", "border", "born", "borrow",
    "boss", "both", "bother", "bottle", "bottom", "boundary", "bowl", "box", "boy", "brain",
    "branch", "brand", "brave", "bread", "break", "breakfast", "breast", "breath", "breathe", "brick",
    "bridge", "brief", "briefly", "bright", "brilliant", "bring", "broad", "broken", "brother", "brown",
    "brush", "budget", "build", "building", "bullet", "bunch", "burden", "burn", "burst", "bury",
    "bus", "business", "busy", "but", "butter", "button", "buy", "buyer", "by", "cabin",
    "cabinet", "cable", "cake", "calculate", "call", "camera", "camp", "campaign", "campus", "can",
    "cancel", "cancer", "candidate", "candle", "candy", "cap", "capable", "capacity", "capital", "captain",
    "capture", "car", "carbon", "card", "care", "career", "careful", "carefully", "carrier", "carry",
    "case", "cash", "cast", "cat", "catch", "category", "cattle", "cause", "ceiling", "celebrate",
    "celebration", "cell", "center", "central", "century", "ceremony", "certain", "certainly", "chain", "chair",
    "chairman", "challenge", "chamber", "champion", "championship", "chance", "change", "changing", "channel", "chapter",
    "character", "characteristic", "characterize", "charge", "charity", "chart", "chase", "cheap", "check", "cheek",
    "cheese", "chef", "chemical", "chemistry", "chest", "chicken", "chief", "child", "childhood", "chip",
    "chocolate", "choice", "cholesterol", "choose", "church", "cigarette", "circle", "circumstance", "cite", "citizen",
    "city", "civil", "civilian", "claim", "class", "classic", "classroom", "clean", "clear", "clearly",
    "client", "climate", "climb", "clinic", "clinical", "clock", "close", "closely", "closer", "clothes",
    "clothing", "cloud", "club", "clue", "cluster", "coach", "coal", "coast", "coat", "code",
    "coffee", "cognitive", "cold", "collapse", "colleague", "collect", "collection", "collective", "college", "colonial",
    "color", "column", "combination", "combine", "come", "comedy", "comfort", "comfortable", "command", "commander",
    "comment", "commercial", "commission", "commit", "commitment", "committee", "common", "communicate", "communication", "community",
    "company", "compare", "comparison", "compete", "competition", "competitive", "competitor", "complain", "complaint", "complete",
    "completely", "complex", "complicated", "component", "compose", "composition", "comprehensive", "computer", "concentrate", "concentration",
    "concept", "concern", "concerned", "concert", "conclude", "conclusion", "concrete", "condition", "conduct", "conference",
    "confidence", "confident", "confirm", "conflict", "confront", "confusion", "congress", "connect", "connection", "consciousness",
    "consensus", "consequence", "conservative", "consider", "considerable", "consideration", "consist", "consistent", "constant", "constantly",
    "constitute", "constitutional", "construct", "construction", "consult", "consultant", "consume", "consumer", "consumption", "contact",
    "contain", "container", "contemporary", "content", "contest", "context", "continue", "continuous", "contract", "contrast",
    "contribute", "contribution", "control", "controversial", "controversy", "convention", "conventional", "conversation", "convert", "conviction",
    "convince", "cook", "cookie", "cooking", "cool", "cooperation", "cop", "cope", "copy", "core",
    "corn", "corner", "corporate", "corporation", "correct", "correspondent", "cost", "cotton", "couch", "could",
    "council", "counsel", "count", "counter", "country", "county", "couple", "courage", "course", "court",
    "cousin", "cover", "coverage", "cow", "crack", "craft", "crash", "crazy", "cream", "create",
    "creation", "creative", "creature", "credit", "crew", "crime", "criminal", "crisis", "criteria", "critic",
    "critical", "criticism", "criticize", "crop", "cross", "crowd", "crucial", "cry", "cultural", "culture",
    "cup", "curious", "current", "currently", "curriculum", "custom", "customer", "cut", "cycle", "dad",
    "daily", "damage", "dance", "danger", "dangerous", "dare", "dark", "darkness", "data", "date",
    "daughter", "day", "dead", "deal", "dealer", "dear", "death", "debate", "debt", "decade",
    "decide", "decision", "deck", "declare", "decline", "decrease", "deep", "deeply", "deer", "defeat",
    "defend", "defendant", "defense", "defensive", "deficit", "define", "definitely", "definition", "degree", "delay",
    "deliver", "delivery", "demand", "democracy", "democratic", "demonstrate", "demonstration", "deny", "department", "depend",
    "dependent", "depending", "depict", "depression", "depth", "deputy", "derive", "describe", "description", "desert",
    "deserve", "design", "designer", "desire", "desk", "desperate", "despite", "destroy", "destruction", "detail",
    "detailed", "detect", "determine", "develop", "developing", "development", "device", "devote", "dialogue", "die",
    "diet", "differ", "difference", "different", "differently", "difficult", "difficulty", "dig", "digital", "dimension",
    "dining", "dinner", "direct", "direction", "directly", "director", "dirt", "dirty", "disability", "disagree",
    "disappear", "disaster", "discipline", "discourse", "discover", "discovery", "discrimination", "discuss", "discussion", "disease",
    "dish", "dismiss", "disorder", "display", "dispute", "distance", "distant", "distinct", "distinction", "distinguish",
    "distribute", "distribution", "district", "diverse", "diversity", "divide", "division", "divorce", "dna", "do",
    "doctor", "document", "dog", "domestic", "dominant", "dominate", "door", "double", "doubt", "down",
    "downtown", "dozen", "draft", "drag", "drama", "dramatic", "dramatically", "draw", "drawing", "dream",
    "dress", "drink", "drive", "driver", "drop", "drug", "dry", "due", "during", "dust",
    "duty", "each", "eager", "ear", "early", "earn", "earnings", "earth", "ease", "easily",
    "east", "eastern", "easy", "eat", "economic", "economics", "economist", "economy", "edge", "edition",
    "editor", "educate", "education", "educational", "educator", "effect", "effective", "effectively", "efficiency", "efficient",
    "effort", "egg", "eight", "either", "elderly", "elect", "election", "electric", "electricity", "electronic",
    "element", "elementary", "eliminate", "elite", "else", "elsewhere", "e-mail", "embrace", "emerge", "emergency",
    "emission", "emotion", "emotional", "emphasis", "emphasize", "employ", "employee", "employer", "employment", "empty",
    "enable", "encounter", "encourage", "end", "enemy", "energy", "enforcement", "engage", "engine", "engineer",
    "engineering", "english", "enhance", "enjoy", "enormous", "enough", "ensure", "enter", "enterprise", "entertainment",
    "entire", "entirely", "entrance", "entry", "environment", "environmental", "episode", "equal", "equally", "equipment",
    "era", "error", "escape", "especially", "essay", "essential", "essentially", "establish", "establishment", "estate",
    "estimate", "etc", "ethics", "ethnic", "european", "evaluate", "evaluation", "even", "evening", "event",
    "eventually", "ever", "every", "everybody", "everyday", "everyone", "everything", "everywhere", "evidence", "evil",
    "evolution", "evolve", "exact", "exactly", "examination", "examine", "example", "exceed", "excellent", "except",
    "exception", "exchange", "exciting", "executive", "exercise", "exhibit", "exhibition", "exist", "existence", "existing",
    "expand", "expansion", "expect", "expectation", "expense", "expensive", "experience", "experiment", "expert", "explain",
    "explanation", "explode", "explore", "explosion", "expose", "exposure", "express", "expression", "extend", "extension",
    "extensive", "extent", "external", "extra", "extraordinary", "extreme", "extremely", "eye", "fabric", "face",
    "facility", "fact", "factor", "factory", "faculty", "fade", "fail", "failure", "fair", "fairly",
    "faith", "fall", "false", "familiar", "family", "famous", "fan", "fantasy", "far", "farm",
    "farmer", "fashion", "fast", "fat", "fate", "father", "fault", "favor", "favorite", "fear",
    "feature", "federal", "fee", "feed", "feel", "feeling", "fellow", "female", "fence", "few",
    "fewer", "fiber", "fiction", "field", "fifteen", "fifth", "fifty", "fight", "fighter", "fighting",
    "figure", "file", "fill", "film", "final", "finally", "finance", "financial", "find", "finding",
    "fine", "finger", "finish", "fire", "firm", "first", "fish", "fishing", "fit", "fitness",
    "five", "fix", "flag", "flame", "flat", "flavor", "flee", "flesh", "flight", "float",
    "floor", "flow", "flower", "fly", "focus", "folk", "follow", "following", "food", "foot",
    "football", "for", "force", "foreign", "forest", "forever", "forget", "form", "formal", "formation",
    "former", "formula", "forth", "fortune", "forward", "found", "foundation", "founder", "four", "fourth",
    "frame", "framework", "free", "freedom", "freeze", "french", "frequency", "frequent", "frequently", "fresh",
    "friend", "friendly", "friendship", "from", "front", "fruit", "frustration", "fuel", "full", "fully",
    "fun", "function", "fund", "fundamental", "funding", "funeral", "funny", "furniture", "furthermore", "future",
    "gain", "galaxy", "gallery", "game", "gang", "gap", "garage", "garden", "garlic", "gas",
    "gate", "gather", "gay", "gaze", "gear", "gender", "gene", "general", "generally", "generate",
    "generation", "genetic", "gentleman", "gently", "german", "gesture", "get", "ghost", "giant", "gift",
    "gifted", "girl", "girlfriend", "give", "given", "glad", "glance", "glass", "global", "glove",
    "go", "goal", "god", "gold", "golden", "golf", "good", "government", "governor", "grab",
    "grade", "gradually", "graduate", "grain", "grand", "grandfather", "grandmother", "grant", "grass", "grave",
    "gray", "great", "greatest", "green", "grocery", "ground", "group", "grow", "growing", "growth",
    "guarantee", "guard", "guess", "guest", "guide", "guideline", "guilty", "gun", "guy", "habit",
    "habitat", "hair", "half", "hall", "hand", "handful", "handle", "hang", "happen", "happy",
    "hard", "hardly", "hat", "hate", "have", "he", "head", "headline", "headquarters", "health",
    "healthy", "hear", "hearing", "heart", "heat", "heaven", "heavily", "heavy", "heel", "height",
    "helicopter", "hell", "hello", "help", "helpful", "her", "here", "heritage", "hero", "herself",
    "hey", "hi", "hide", "high", "highlight", "highly", "highway", "hill", "him", "himself",
    "hint", "hip", "hire", "his", "historian", "historic", "historical", "history", "hit", "hold",
    "hole", "holiday", "holy", "home", "homeless", "honest", "honey", "honor", "hope", "horizon",
    "horror", "horse", "hospital", "host", "hot", "hotel", "hour", "house", "household", "housing",
    "how", "however", "huge", "human", "humor", "hundred", "hungry", "hunter", "hunting", "hurt",
    "husband", "hypothesis", "i", "ice", "idea", "ideal", "identification", "identify", "identity", "ie",
    "if", "ignore", "ill", "illegal", "illness", "illustrate", "image", "imagination", "imagine", "immediate",
    "immediately", "immigrant", "immigration", "impact", "implement", "implication", "imply", "importance", "important", "impose",
    "impossible", "impress", "impression", "impressive", "improve", "improvement", "in", "incentive", "incident", "include",
    "including", "income", "incorporate", "increase", "increased", "increasing", "increasingly", "incredible", "indeed", "independence",
    "independent", "index", "indian", "indicate", "indication", "individual", "industrial", "industry", "infant", "infection",
    "inflation", "influence", "inform", "information", "ingredient", "initial", "initially", "initiative", "injury", "inner",
    "innocent", "inquiry", "inside", "insight", "insist", "inspire", "install", "instance", "instead", "institution",
    "institutional", "instruction", "instructor", "instrument", "insurance", "intellectual", "intelligence", "intend", "intense", "intensity",
    "intention", "interaction", "interest", "interested", "interesting", "internal", "international", "internet", "interpret", "interpretation",
    "intervention", "interview", "into", "introduce", "introduction", "invasion", "invest", "investigate", "investigation", "investigator",
    "investment", "investor", "invite", "involve", "involved", "involvement", "iron", "islamic", "island", "isolate",
    "issue", "it", "item", "its", "itself", "jacket", "jail", "jam", "january", "japanese",
    "jar", "jaw", "jazz", "jeans", "jet", "jew", "jewish", "job", "join", "joint",
    "joke", "journal", "journalist", "journey", "joy", "judge", "judgment", "juice", "jump", "junior",
    "jury", "just", "justice", "justify", "keep", "key", "kick", "kid", "kill", "killer",
    "killing", "kind", "king", "kiss", "kitchen", "knee", "knife", "knock", "know", "knowledge",
    "lab", "label", "labor", "laboratory", "lack", "lad", "ladder", "lady", "lake", "land",
    "landscape", "language", "lap", "large", "largely", "last", "late", "later", "latin", "latter",
    "laugh", "laughter", "launch", "law", "lawn", "lawsuit", "lawyer", "lay", "layer", "lead",
    "leader", "leadership", "leading", "leaf", "league", "lean", "learn", "learning", "least", "leather",
    "leave", "left", "leg", "legacy", "legal", "legend", "legislation", "legitimate", "lemon", "length",
    "less", "lesson", "let", "letter", "level", "liberal", "library", "license", "lie", "life",
    "lifestyle", "lifetime", "lift", "light", "like", "likely", "limit", "limitation", "limited", "line",
    "link", "lip", "list", "listen", "literally", "literary", "literature", "little", "live", "living",
    "load", "loan", "local", "locate", "location", "lock", "long", "long-term", "look", "loose",
    "lose", "loss", "lost", "lot", "lots", "loud", "love", "lovely", "lover", "low",
    "lower", "luck", "lucky", "lunch", "lung", "machine", "mad", "magazine", "mail", "main",
    "mainly", "maintain", "maintenance", "major", "majority", "make", "maker", "makeup", "male", "mall",
    "man", "manage", "management", "manager", "manner", "manufacturer", "manufacturing", "many", "map", "margin",
    "mark", "market", "marketing", "marriage", "married", "marry", "mask", "mass", "massive", "master",
    "match", "material", "math", "matter", "may", "maybe", "mayor", "me", "meal", "mean",
    "meaning", "meanwhile", "measure", "measurement", "meat", "mechanism", "media", "medical", "medication", "medicine",
    "medium", "meet", "meeting", "member", "membership", "memory", "mental", "mention", "menu", "mere",
    "merely", "mess", "message", "metal", "meter", "method", "mexican", "middle", "might", "military",
    "milk", "million", "mind", "mine", "minister", "minor", "minority", "minute", "miracle", "mirror",
    "miss", "missile", "mission", "mistake", "mix", "mixture", "mm-hmm", "mode", "model", "moderate",
    "modern", "modest", "mom", "moment", "money", "monitor", "month", "mood", "moon", "moral",
    "more", "moreover", "morning", "mortgage", "most", "mostly", "mother", "motion", "motivation", "motor",
    "mount", "mountain", "mouse", "mouth", "move", "movement", "movie", "mr", "mrs", "ms",
    "much", "multiple", "murder", "muscle", "museum", "music", "musical", "musician", "must", "mutual",
    "my", "myself", "mystery", "myth", "nail", "naked", "name", "narrative", "narrow", "nation",
    "national", "native", "natural", "naturally", "nature", "near", "nearby", "nearly", "necessarily", "necessary",
    "neck", "need", "negative", "negotiate", "negotiation", "neighbor", "neighborhood", "neither", "nerve", "nervous",
    "nest", "net", "network", "never", "nevertheless", "new", "newly", "news", "newspaper", "next",
    "nice", "night", "nine", "no", "nobody", "nod", "noise", "nomination", "none", "nonetheless",
    "nor", "normal", "normally", "north", "northern", "nose", "not", "note", "nothing", "notice",
    "notion", "novel", "now", "nowhere", "nuclear", "number", "numerous", "nurse", "nut", "object",
    "objective", "obligation", "observation", "observe", "observer", "obtain", "obvious", "obviously", "occasion", "occasionally",
    "occupation", "occupy", "occur", "ocean", "odd", "odds", "of", "off", "offense", "offensive",
    "offer", "office", "officer", "official", "often", "oh", "oil", "ok", "okay", "old",
    "olympic", "on", "once", "one", "ongoing", "onion", "online", "only", "onto", "open",
    "opening", "operate", "operating", "operation", "operator", "opinion", "opponent", "opportunity", "oppose", "opposite",
    "opposition", "option", "or", "orange", "order", "ordinary", "organic", "organization", "organize", "orientation",
    "origin", "original", "originally", "other", "others", "otherwise", "ought", "our", "ourselves", "out",
    "outcome", "outside", "oven", "over", "overall", "overcome", "overlook", "overnight", "overseas", "overwhelming",
    "owe", "own", "owner", "pace", "pack", "package", "page", "pain", "painful", "paint",
    "painter", "painting", "pair", "pale", "palestinian", "palm", "pan", "panel", "pant", "paper",
    "parent", "park", "parking", "part", "participant", "participate", "participation", "particular", "particularly", "partly",
    "partner", "partnership", "party", "pass", "passage", "passenger", "passion", "past", "patch", "path",
    "patient", "pattern", "pause", "pay", "payment", "pc", "peace", "peak", "peer", "pen",
    "penalty", "people", "pepper", "per", "perceive", "percentage", "perception", "perfect", "perfectly", "perform",
    "performance", "perhaps", "period", "permanent", "permission", "permit", "person", "personal", "personality", "personally",
    "personnel", "perspective", "persuade", "pet", "phase", "phenomenon", "philosophy", "phone", "photo", "photograph",
    "photographer", "phrase", "physical", "physically", "physician", "piano", "pick", "picture", "pie", "piece",
    "pile", "pilot", "pin", "pink", "pioneer", "pipe", "pitch", "place", "plan", "plane",
    "planet", "planning", "plant", "plastic", "plate", "platform", "play", "player", "please", "pleasure",
    "plenty", "plot", "plus", "pm", "pocket", "poem", "poet", "poetry", "point", "pole",
    "police", "policy", "political", "politically", "politician", "politics", "poll", "pollution", "pool", "poor",
    "pop", "popular", "population", "porch", "port", "portion", "portrait", "pose", "position", "positive",
    "possess", "possibility", "possible", "possibly", "post", "pot", "potato", "potential", "potentially", "pound",
    "pour", "poverty", "powder", "power", "powerful", "practical", "practice", "pray", "prayer", "precisely",
    "predict", "prefer", "preference", "pregnancy", "pregnant", "preparation", "prepare", "prescription", "presence", "present",
    "presentation", "preserve", "president", "presidential", "press", "pressure", "pretend", "pretty", "prevent", "prevention",
    "previous", "previously", "price", "pride", "priest", "primarily", "primary", "prime", "principal", "principle",
    "print", "prior", "priority", "prison", "prisoner", "privacy", "private", "probably", "problem", "procedure",
    "proceed", "process", "produce", "producer", "product", "production", "profession", "professional", "professor", "profile",
    "profit", "program", "progress", "project", "prominent", "promise", "promote", "prompt", "proof", "proper",
    "properly", "property", "proportion", "proposal", "propose", "proposed", "prosecutor", "prospect", "protect", "protection",
    "protein", "protest", "proud", "prove", "provide", "provider", "province", "provision", "psychological", "psychologist",
    "psychology", "public", "publication", "publicly", "publish", "publisher", "pull", "punishment", "purchase", "pure",
    "purpose", "pursue", "push", "put", "qualify", "quality", "quarter", "queen", "question", "quick",
    "quickly", "quiet", "quietly", "quit", "quite", "quote", "race", "racial", "radical", "radio",
    "rail", "rain", "raise", "range", "rank", "rapid", "rapidly", "rare", "rarely", "rate",
    "rather", "rating", "ratio", "raw", "reach", "react", "reaction", "read", "reader", "reading",
    "ready", "real", "reality", "realize", "really", "reason", "reasonable", "recall", "receive", "recent",
    "recently", "recipe", "recognition", "recognize", "recommend", "recommendation", "record", "recording", "recover", "recovery",
    "recruit", "red", "reduce", "reduction", "refer", "reference", "reflect", "reflection", "reform", "refugee",
    "refuse", "regard", "regarding", "regardless", "regime", "region", "regional", "register", "regular", "regularly",
    "regulate", "regulation", "reinforce", "reject", "relate", "relation", "relationship", "relative", "relatively", "relax",
    "release", "relevant", "relief", "religion", "religious", "rely", "remain", "remaining", "remarkable", "remember",
    "remind", "remote", "remove", "repeat", "repeatedly", "replace", "reply", "report", "reporter", "represent",
    "representation", "representative", "republican", "reputation", "request", "require", "requirement", "research", "researcher", "resemble",
    "reservation", "resident", "resist", "resistance", "resolution", "resolve", "resort", "resource", "respect", "respond",
    "response", "responsibility", "responsible", "rest", "restaurant", "restore", "restriction", "result", "retain", "retire",
    "retirement", "return", "reveal", "revenue", "review", "revolution", "rhythm", "rice", "rich", "rid",
    "ride", "rifle", "right", "ring", "rise", "risk", "river", "road", "rock", "role",
    "roll", "romantic", "roof", "room", "root", "rope", "rose", "rough", "roughly", "round",
    "route", "routine", "row", "rub", "rule", "run", "running", "rural", "rush", "russian",
    "sacred", "sad", "safe", "safety", "sake", "salad", "salary", "sale", "sales", "salt",
    "same", "sample", "sanction", "sand", "satellite", "satisfaction", "satisfy", "sauce", "save", "saving",
    "say", "scale", "scandal", "scared", "scenario", "scene", "schedule", "scheme", "scholar", "scholarship",
    "school", "science", "scientific", "scientist", "scope", "score", "scream", "screen", "script", "sea",
    "search", "season", "seat", "second", "secret", "secretary", "section", "sector", "secure", "security",
    "see", "seed", "seek", "seem", "segment", "seize", "select", "selection", "self", "sell",
    "senate", "senator", "send", "senior", "sense", "sensitive", "sentence", "separate", "sequence", "series",
    "serious", "seriously", "serve", "service", "session", "set", "setting", "settle", "settlement", "seven",
    "several", "severe", "sex", "sexual", "shade", "shadow", "shake", "shall", "shape", "share",
    "sharp", "she", "sheet", "shelf", "shell", "shelter", "shift", "shine", "ship", "shirt",
    "shit", "shock", "shoe", "shoot", "shooting", "shop", "shopping", "shore", "short", "shortly",
    "shot", "should", "shoulder", "shout", "show", "shower", "shrug", "shut", "sick", "side",
    "sigh", "sight", "sign", "signal", "significance", "significant", "significantly", "silence", "silent", "silver",
    "similar", "similarly", "simple", "simply", "sin", "since", "sing", "singer", "single", "sink",
    "sir", "sister", "sit", "site", "situation", "six", "size", "ski", "skill", "skin",
    "sky", "slave", "sleep", "slice", "slide", "slight", "slightly", "slip", "slow", "slowly",
    "small", "smart", "smell", "smile", "smoke", "smooth", "snap", "snow", "so", "so-called",
    "soccer", "social", "society", "soft", "software", "soil", "solar", "soldier", "solid", "solution",
    "solve", "some", "somebody", "somehow", "someone", "something", "sometimes", "somewhat", "somewhere", "son",
    "song", "soon", "sophisticated", "sorry", "sort", "soul", "sound", "soup", "source", "south",
    "southern", "soviet", "space", "spanish", "speak", "speaker", "special", "specialist", "species", "specific",
    "specifically", "speech", "speed", "spend", "spending", "spin", "spirit", "spiritual", "split", "spokesman",
    "sport", "spot", "spread", "spring", "square", "squeeze", "stable", "staff", "stage", "stair",
    "stake", "stand", "standard", "standing", "star", "stare", "start", "state", "statement", "station",
    "statistics", "status", "stay", "steady", "steal", "steel", "step", "stick", "still", "stir",
    "stock", "stomach", "stone", "stop", "storage", "store", "storm", "story", "straight", "strange",
    "stranger", "strategic", "strategy", "stream", "street", "strength", "strengthen", "stress", "stretch", "strike",
    "string", "strip", "stroke", "strong", "strongly", "structure", "struggle", "student", "studio", "study",
    "stuff", "stupid", "style", "subject", "submit", "subsequent", "substance", "substantial", "succeed", "success",
    "successful", "successfully", "such", "sudden", "suddenly", "suffer", "sufficient", "sugar", "suggest", "suggestion",
    "suicide", "suit", "summer", "summit", "sun", "super", "supply", "support", "supporter", "suppose",
    "supposed", "supreme", "sure", "surely", "surface", "surgery", "surprise", "surprised", "surprising", "surprisingly",
    "surround", "survey", "survival", "survive", "survivor", "suspect", "sustain", "swear", "sweep", "sweet",
    "swim", "swing", "switch", "symbol", "symptom", "system", "table", "tablespoon", "tactic", "tail",
    "take", "tale", "talent", "talk", "tall", "tank", "tap", "tape", "target", "task",
    "taste", "tax", "taxpayer", "tea", "teach", "teacher", "teaching", "team", "tear", "teaspoon",
    "technical", "technique", "technology", "teen", "teenager", "telephone", "telescope", "television", "tell", "temperature",
    "temporary", "ten", "tend", "tendency", "tennis", "tension", "tent", "term", "terms", "terrible",
    "territory", "terror", "terrorism", "terrorist", "test", "testify", "testimony", "testing", "text", "than",
    "thank", "thanks", "that", "the", "theater", "their", "them", "theme", "themselves", "then",
    "theory", "therapy", "there", "therefore", "these", "they", "thick", "thin", "thing", "think",
    "thinking", "third", "thirty", "this", "those", "though", "thought", "thousand", "threat", "threaten",
    "three", "throat", "through", "throughout", "throw", "thus", "ticket", "tie", "tight", "time",
    "tiny", "tip", "tire", "tired", "tissue", "title", "to", "tobacco", "today", "toe",
    "together", "tomato", "tomorrow", "tone", "tongue", "tonight", "too", "tool", "tooth", "top",
    "topic", "toss", "total", "totally", "touch", "tough", "tour", "tourist", "tournament", "toward",
    "towards", "tower", "town", "toy", "trace", "track", "trade", "tradition", "traditional", "traffic",
    "tragedy", "trail", "train", "training", "transfer", "transform", "transformation", "transition", "translate", "transportation",
    "travel", "treat", "treatment", "treaty", "tree", "tremendous", "trend", "trial", "tribe", "trick",
    "trip", "trouble", "truck", "true", "truly", "trust", "truth", "try", "tube", "tunnel",
    "turn", "tv", "twelve", "twenty", "twice", "twin", "two", "type", "typical", "typically",
    "ugly", "ultimate", "ultimately", "unable", "uncle", "under", "undergo", "understand", "understanding", "undertake",
    "unemployment", "unexpected", "unfair", "unfold", "unfortunately", "unhappy", "uniform", "union", "unique", "unit",
    "united", "universal", "universe", "university", "unknown", "unless", "unlike", "unlikely", "until", "unusual",
    "up", "upon", "upper", "urban", "urge", "us", "use", "used", "useful", "user",
    "usual", "usually", "utility", "vacation", "valley", "valuable", "value", "variable", "variation", "variety",
    "various", "vary", "vast", "vegetable", "vehicle", "venture", "version", "versus", "very", "vessel",
    "veteran", "via", "victim", "victory", "video", "view", "viewer", "village", "violate", "violation",
    "violence", "violent", "virtually", "virtue", "virus", "visible", "vision", "visit", "visitor", "visual",
    "vital", "voice", "volume", "volunteer", "vote", "voter", "vs", "vulnerable", "wage", "wait",
    "wake", "walk", "wall", "wander", "want", "war", "warm", "warn", "warning", "wash",
    "waste", "watch", "water", "wave", "way", "we", "weak", "wealth", "wealthy", "weapon",
    "wear", "weather", "wedding", "week", "weekend", "weekly", "weigh", "weight", "welcome", "welfare",
    "well", "west", "western", "wet", "whale", "what", "whatever", "wheat", "wheel", "when",
    "whenever", "where", "whereas", "whether", "which", "while", "whisper", "white", "who", "whole",
    "whom", "whose", "why", "wide", "widely", "widespread", "wife", "wild", "will", "willing",
    "win", "wind", "window", "wine", "wing", "winner", "winter", "wipe", "wire", "wisdom",
    "wise", "wish", "with", "withdraw", "within", "without", "witness", "woman", "wonder", "wonderful",
    "wood", "wooden", "word", "work", "worker", "working", "works", "workshop", "world", "worried",
    "worry", "worth", "would", "wound", "wrap", "write", "writer", "writing", "wrong", "yard",
    "yeah", "year", "yell", "yellow", "yes", "yesterday", "yet", "yield", "you", "young",
    "your", "yours", "yourself", "youth", "zone"
}

@app.route('/')
def home():
    return render_template('spell-checker.html')

@app.route('/check', methods=['POST'])
def check_spelling():
    data = request.get_json()
    text = data.get('text', '')
    
    # Simple word extraction
    words = re.findall(r'\b\w+\b', text.lower())
    
    correct = []
    wrong = []
    
    for word in words:
        if word in WORDS:
            if word not in correct:
                correct.append(word)
        else:
            if word not in wrong:
                wrong.append(word)
    
    # Get suggestions for wrong words
    suggestions = {}
    for word in wrong:
        suggestions[word] = get_suggestions(word)
    
    return jsonify({
        "correct": correct,
        "wrong": wrong,
        "suggestions": suggestions
    })

def get_suggestions(word):
    """Get suggestions for a misspelled word"""
    suggestions = []
    word_lower = word.lower()
    
    # If word is already correct, return empty
    if word_lower in WORDS:
        return suggestions
    
    # Check common variations
    variations = [
        # Common misspellings
        word_lower + 'e',  # hav -> have
        word_lower[:-1] if word_lower.endswith('e') else word_lower,  # mistake -> mistak
        word_lower + 's',  # mistake -> mistakes
        word_lower[:-1] if word_lower.endswith('s') else word_lower,  # mistakes -> mistake
    ]
    
    # Check for words in dictionary that are similar
    for dict_word in WORDS:
        if len(dict_word) >= 3:  # Only check reasonable length words
            # Check if it's a close match
            if (dict_word.startswith(word_lower[:3]) or 
                dict_word.endswith(word_lower[-3:]) or
                dict_word in word_lower or
                word_lower in dict_word):
                if len(suggestions) < 5:  # Limit to 5 suggestions
                    suggestions.append(dict_word)
    
    return suggestions[:5]  # Return max 5 suggestions

if __name__ == '__main__':
    print("Spell Checker Running...")
    print("Open: http://127.0.0.1:5000")
    app.run(debug=True, port=5000)